Repository ds-wizard/engine-frontend, pull requests merged in 2021-09, with the labels that each got.

#158 Release 3.3.0
  .github/workflows/main.yml
  engine-shared/elm/Shared/Api.elm
  engine-shared/elm/Shared/Api/Questionnaires.elm
  engine-shared/elm/Shared/Api/Users.elm
  engine-shared/elm/Shared/Data/Pagination.elm
  engine-shared/elm/Shared/Data/PaginationQueryString.elm
  engine-shared/elm/Shared/Error/ServerError.elm
  engine-wizard/elm/Wizard/Common/Components/Listing/Update.elm
  engine-wizard/elm/Wizard/Common/Components/Listing/View.elm
  engine-wizard/elm/Wizard/Common/Components/SummaryReport.elm
  engine-wizard/elm/Wizard/Common/Provisioning/DefaultLocale.elm
  engine-wizard/elm/Wizard/Common/View/Page.elm
  engine-wizard/elm/Wizard/Dashboard/Update.elm
  engine-wizard/elm/Wizard/Documents/Index/Update.elm
  engine-wizard/elm/Wizard/Documents/Index/View.elm
  engine-wizard/elm/Wizard/Documents/Routing.elm
  engine-wizard/elm/Wizard/KMEditor/Editor/KMEditor/View/Editors.elm
  engine-wizard/elm/Wizard/KMEditor/Index/Update.elm
  engine-wizard/elm/Wizard/KMEditor/Index/View.elm
  engine-wizard/elm/Wizard/KMEditor/Routing.elm
  engine-wizard/elm/Wizard/KnowledgeModels/Index/Update.elm
  engine-wizard/elm/Wizard/KnowledgeModels/Index/View.elm
  engine-wizard/elm/Wizard/Projects/Create/TemplateCreate/Update.elm
  engine-wizard/elm/Wizard/Projects/Create/View.elm
  engine-wizard/elm/Wizard/Projects/CreateMigration/View.elm
  engine-wizard/elm/Wizard/Projects/Detail/Components/Preview.elm
  engine-wizard/elm/Wizard/Projects/Detail/Documents/Update.elm
  engine-wizard/elm/Wizard/Projects/Detail/Documents/View.elm
  engine-wizard/elm/Wizard/Projects/Detail/View.elm
  engine-wizard/elm/Wizard/Projects/Index/Models.elm
  engine-wizard/elm/Wizard/Projects/Index/Update.elm
  engine-wizard/elm/Wizard/Projects/Index/View.elm
  engine-wizard/elm/Wizard/Projects/Models.elm
  engine-wizard/elm/Wizard/Projects/Routes.elm
  engine-wizard/elm/Wizard/Projects/Routing.elm
  engine-wizard/elm/Wizard/Projects/Subscriptions.elm
  engine-wizard/elm/Wizard/Projects/Update.elm
  engine-wizard/elm/Wizard/Projects/View.elm
  engine-wizard/elm/Wizard/Routes.elm
  engine-wizard/elm/Wizard/Templates/Index/Update.elm
  engine-wizard/elm/Wizard/Templates/Index/View.elm
  engine-wizard/elm/Wizard/Users/Index/Models.elm
  engine-wizard/elm/Wizard/Users/Index/Update.elm
  engine-wizard/elm/Wizard/Users/Index/View.elm
  engine-wizard/elm/Wizard/Users/Models.elm
  engine-wizard/elm/Wizard/Users/Routes.elm
  engine-wizard/elm/Wizard/Users/Routing.elm
  engine-wizard/elm/Wizard/Users/Subscriptions.elm
  engine-wizard/elm/Wizard/Users/Update.elm
  engine-wizard/elm/Wizard/Users/View.elm
  engine-wizard/scss/_variables.scss
  engine-wizard/scss/modules/Projects/_Detail.scss
  package-lock.json
  package.json
  scripts/build.sh
  webpack.config.js
Labels: release

#159 Release 3.3.0 (develop)
  package-lock.json
  package.json
Labels: release

#160 [DSW-1175] Fix follow-up indication
  engine-wizard/elm/Wizard/Common/Components/Questionnaire.elm
Labels: bugfix

#162 [DSW-1183] Fix creating project from KM preview
  engine-shared/elm/Shared/Data/Document.elm
  engine-wizard/elm/Wizard.elm
  engine-wizard/elm/Wizard/Common/Feature.elm
  engine-wizard/elm/Wizard/Common/Menu/View.elm
  engine-wizard/elm/Wizard/Common/View/Layout.elm
  engine-wizard/elm/Wizard/Documents/Index/View.elm
  engine-wizard/elm/Wizard/Documents/Routing.elm
  engine-wizard/elm/Wizard/KMEditor/Index/View.elm
  engine-wizard/elm/Wizard/KMEditor/Routing.elm
  engine-wizard/elm/Wizard/KnowledgeModels/Detail/View.elm
  engine-wizard/elm/Wizard/KnowledgeModels/Index/View.elm
  engine-wizard/elm/Wizard/KnowledgeModels/Preview/View.elm
  engine-wizard/elm/Wizard/KnowledgeModels/Routing.elm
  engine-wizard/elm/Wizard/Projects/Create/View.elm
  engine-wizard/elm/Wizard/Projects/Detail/Components/Settings.elm
  engine-wizard/elm/Wizard/Projects/Detail/Documents/View.elm
  engine-wizard/elm/Wizard/Projects/Detail/View.elm
  engine-wizard/elm/Wizard/Projects/Index/View.elm
  engine-wizard/elm/Wizard/Projects/Routing.elm
  engine-wizard/elm/Wizard/Registry/Routing.elm
  engine-wizard/elm/Wizard/Routing.elm
  engine-wizard/elm/Wizard/Settings/Routing.elm
  engine-wizard/elm/Wizard/Templates/Detail/View.elm
  engine-wizard/elm/Wizard/Templates/Index/View.elm
  engine-wizard/elm/Wizard/Templates/Routing.elm
  engine-wizard/elm/Wizard/Users/Routing.elm
Labels: bugfix

#165 [DSW-1189] Update GitHub workflows to work with dependabot
  .github/dependabot.yml
  .github/workflows/main.yml
Labels: chore

#166 [DSW-1191] Add CONTRIBUTING and SECURITY
  CONTRIBUTING.md
  README.md
  SECURITY.md
Labels: chore

#184 [DSW-1186] Add comments to projects
  engine-shared/elm/Shared/Common/Provisioning/DefaultLocale.elm
  engine-shared/elm/Shared/Data/Questionnaire/QuestionnaireSharing.elm
  engine-shared/elm/Shared/Data/Questionnaire/QuestionnaireVisibility.elm
  engine-shared/elm/Shared/Data/QuestionnaireDetail.elm
  engine-shared/elm/Shared/Data/QuestionnaireDetail/Comment.elm
  engine-shared/elm/Shared/Data/QuestionnaireDetail/CommentThread.elm
  engine-shared/elm/Shared/Data/QuestionnaireDetail/QuestionnaireEvent.elm
  engine-shared/elm/Shared/Data/QuestionnaireDetail/QuestionnaireEvent/AddCommentData.elm
  engine-shared/elm/Shared/Data/QuestionnaireDetail/QuestionnaireEvent/DeleteCommentData.elm
  engine-shared/elm/Shared/Data/QuestionnaireDetail/QuestionnaireEvent/DeleteCommentThreadData.elm
  engine-shared/elm/Shared/Data/QuestionnaireDetail/QuestionnaireEvent/EditCommentData.elm
  engine-shared/elm/Shared/Data/QuestionnaireDetail/QuestionnaireEvent/ReopenCommentThreadData.elm
  engine-shared/elm/Shared/Data/QuestionnaireDetail/QuestionnaireEvent/ResolveCommentThreadData.elm
  engine-shared/elm/Shared/Data/QuestionnairePerm.elm
  engine-shared/elm/Shared/Data/QuestionnairePermission.elm
  engine-wizard/elm/Wizard/Common/Components/Questionnaire.elm
  engine-wizard/elm/Wizard/Common/Components/Questionnaire/History.elm
  engine-wizard/elm/Wizard/Common/Feature.elm
  engine-wizard/elm/Wizard/Common/Html.elm
  engine-wizard/elm/Wizard/Common/Provisioning/DefaultIconSet.elm
  engine-wizard/elm/Wizard/Common/Provisioning/DefaultLocale.elm
  engine-wizard/elm/Wizard/Common/View/UserIcon.elm
  engine-wizard/elm/Wizard/Projects/Common/QuestionnaireEditFormMemberPerms.elm
  engine-wizard/elm/Wizard/Projects/Detail/Update.elm
  engine-wizard/elm/Wizard/Users/Index/View.elm
  engine-wizard/scss/_elements.scss
  engine-wizard/scss/_variables.scss
  engine-wizard/scss/modules/Common/Components/_Questionnaire.scss
Labels: feature

#186 [DSW-1197] Fix missing forkOf and mergeCheckpoint package
  engine-wizard/elm/Wizard/KnowledgeModels/Detail/View.elm
Labels: bugfix
