Repository ds-wizard/engine-frontend, pull requests merged in 2023-11, with the labels that each got.

#1001 Release 4.0.0 (develop)
  .github/workflows/pot.yml
  package-lock.json
  package.json
Labels: release

#1005 Hotfix 4.0.1
  .github/workflows/registry.yml
  .github/workflows/wizard.yml
  engine-registry/scss/_version.scss
  engine-wizard/elm/Wizard/Common/Menu/View.elm
  engine-wizard/elm/Wizard/Common/View/ExternalLoginButton.elm
  engine-wizard/elm/Wizard/Public/Login/Msgs.elm
  engine-wizard/elm/Wizard/Public/Login/Update.elm
  engine-wizard/elm/Wizard/Public/Login/View.elm
  engine-wizard/img/favicon/android-chrome-192x192.png
  engine-wizard/img/favicon/android-chrome-512x512.png
  engine-wizard/img/favicon/apple-touch-icon.png
  engine-wizard/img/favicon/favicon-16x16.png
  engine-wizard/img/favicon/favicon-32x32.png
  engine-wizard/img/favicon/favicon.ico
  engine-wizard/img/favicon/mstile-144x144.png
  engine-wizard/img/favicon/mstile-150x150.png
  engine-wizard/img/favicon/mstile-310x150.png
  engine-wizard/img/favicon/mstile-310x310.png
  engine-wizard/img/favicon/mstile-70x70.png
  engine-wizard/img/favicon/safari-pinned-tab.svg
  engine-wizard/img/favicon/site.webmanifest
  engine-wizard/index.ejs
  engine-wizard/scss/_version.scss
  engine-wizard/scss/elements/_table.scss
  scripts/build_info.sh
  scripts/replace_version.sh
Labels: hotfix

#1006 Hotfix 4.0.1 (develop)
  .github/workflows/registry.yml
  .github/workflows/wizard.yml
  engine-registry/scss/_version.scss
  engine-wizard/elm/Wizard/Common/Menu/View.elm
  engine-wizard/elm/Wizard/Common/View/ExternalLoginButton.elm
  engine-wizard/elm/Wizard/Public/Login/Msgs.elm
  engine-wizard/elm/Wizard/Public/Login/Update.elm
  engine-wizard/elm/Wizard/Public/Login/View.elm
  engine-wizard/img/favicon/android-chrome-192x192.png
  engine-wizard/img/favicon/android-chrome-512x512.png
  engine-wizard/img/favicon/apple-touch-icon.png
  engine-wizard/img/favicon/favicon-16x16.png
  engine-wizard/img/favicon/favicon-32x32.png
  engine-wizard/img/favicon/favicon.ico
  engine-wizard/img/favicon/mstile-144x144.png
  engine-wizard/img/favicon/mstile-150x150.png
  engine-wizard/img/favicon/mstile-310x150.png
  engine-wizard/img/favicon/mstile-310x310.png
  engine-wizard/img/favicon/mstile-70x70.png
  engine-wizard/img/favicon/safari-pinned-tab.svg
  engine-wizard/img/favicon/site.webmanifest
  engine-wizard/index.ejs
  engine-wizard/scss/_version.scss
  engine-wizard/scss/elements/_table.scss
  scripts/build_info.sh
  scripts/replace_version.sh
Labels: hotfix

#1007 [DSW-2117] Fix primary color on some elements
  engine-wizard/scss/bootstrap/_overrides.scss
Labels: bugfix

#1011 Hotfix 4.0.2
  engine-wizard/elm/Wizard/Common/Menu/Msgs.elm
  engine-wizard/elm/Wizard/Common/Menu/Update.elm
  engine-wizard/elm/Wizard/Common/Menu/View.elm
  engine-wizard/elm/Wizard/Update.elm
  engine-wizard/index.js
  engine-wizard/js/ports/session.js
Labels: hotfix

#1012 Hotfix 4.0.2 (develop)
  engine-wizard/elm/Wizard/Common/Menu/Msgs.elm
  engine-wizard/elm/Wizard/Common/Menu/Update.elm
  engine-wizard/elm/Wizard/Common/Menu/View.elm
  engine-wizard/elm/Wizard/Update.elm
  engine-wizard/index.js
  engine-wizard/js/ports/session.js
Labels: hotfix

#1008 [DSW-1857] Update deprecated set-output in GitHub CI
  .github/workflows/pot.yml
Labels: chore

#1014 [DSW-2127] Fix broken pagination when deleting last item in list views
  engine-wizard/elm/Wizard/Common/Components/Listing/Update.elm
Labels: bugfix

#1015 Update integration fields
  engine-shared/elm/Shared/Data/Event/AddIntegrationApiEventData.elm
  engine-shared/elm/Shared/Data/Event/AddIntegrationWidgetEventData.elm
  engine-shared/elm/Shared/Data/Event/EditIntegrationApiEventData.elm
  engine-shared/elm/Shared/Data/Event/EditIntegrationEventData.elm
  engine-shared/elm/Shared/Data/Event/EditIntegrationWidgetEventData.elm
  engine-shared/elm/Shared/Data/KnowledgeModel/Integration.elm
  engine-shared/elm/Shared/Data/KnowledgeModel/Integration/ApiIntegrationData.elm
  engine-shared/elm/Shared/Data/KnowledgeModel/Integration/CommonIntegrationData.elm
  engine-shared/elm/Shared/Data/QuestionnaireDetail/Reply/ReplyValue/IntegrationReplyType.elm
  engine-shared/elm/Shared/Data/TypeHint.elm
  engine-wizard/elm/Wizard/Common/Components/Questionnaire.elm
  engine-wizard/elm/Wizard/Common/Components/Questionnaire/Importer/ImporterEvent.elm
  engine-wizard/elm/Wizard/KMEditor/Editor/Common/EditorBranch.elm
  engine-wizard/elm/Wizard/KMEditor/Editor/Components/KMEditor.elm
  engine-wizard/elm/Wizard/KMEditor/Migration/View.elm
  tests/Shared/Data/EventTest.elm
  tests/Shared/Data/KnowledgeModel/IntegrationTest.elm
  tests/Shared/Data/KnowledgeModel/KnowledgeModelEntitiesTest.elm
  tests/Shared/Data/KnowledgeModelTest.elm
Labels: chore
