Repository ds-wizard/engine-frontend, pull requests merged in 2023-02, with the labels that each got.

#645 [DSW-1636] Fix importing KM with newer metamodel version
  engine-shared/elm/Shared/Error/ServerError.elm
Labels: bugfix

#646 [DSW-1683] Fix import answers visibility
  engine-wizard/elm/Wizard/Common/Components/Questionnaire.elm
Labels: bugfix

#656 Release 3.20.0 (develop)
  package-lock.json
  package.json
  wizard-style-builder/package-lock.json
  wizard-style-builder/package.json
Labels: release

#657 Hotfix 3.20.1
  engine-registry/elm/Registry.elm
  engine-registry/elm/Registry/Common/Entities/DocumentTemplate.elm
  engine-registry/elm/Registry/Common/Entities/DocumentTemplateDetail.elm
  engine-registry/elm/Registry/Common/Requests.elm
  engine-registry/elm/Registry/Pages/DocumentTemplateDetail.elm
  engine-registry/elm/Registry/Pages/DocumentTemplates.elm
  engine-registry/elm/Registry/Pages/LocalesDetail.elm
  engine-registry/elm/Registry/Routing.elm
  package-lock.json
  package.json
  wizard-style-builder/package-lock.json
  wizard-style-builder/package.json
Labels: hotfix

#658 Hotfix 3.20.1 (develop)
  engine-registry/elm/Registry.elm
  engine-registry/elm/Registry/Common/Entities/DocumentTemplate.elm
  engine-registry/elm/Registry/Common/Entities/DocumentTemplateDetail.elm
  engine-registry/elm/Registry/Common/Requests.elm
  engine-registry/elm/Registry/Pages/DocumentTemplateDetail.elm
  engine-registry/elm/Registry/Pages/DocumentTemplates.elm
  engine-registry/elm/Registry/Pages/LocalesDetail.elm
  engine-registry/elm/Registry/Routing.elm
  package-lock.json
  package.json
  wizard-style-builder/package-lock.json
  wizard-style-builder/package.json
Labels: hotfix

#660 [DSW-1695] Improve OpenID button style naming
  engine-wizard/elm/Wizard/Settings/Authentication/View.elm
Labels: feature

#659 [DSW-1692] Remove KM ID from project list view
  engine-wizard/elm/Wizard/Projects/Index/View.elm
Labels: feature

#661 [DSW-1696] Fix private default visibility description
  engine-shared/elm/Shared/Data/Questionnaire/QuestionnaireVisibility.elm
Labels: bugfix

#662 [DSW-1697] Fix main menu highlight when document template editor is open
  engine-wizard/elm/Wizard/Routes.elm
Labels: bugfix

#663 [DSW-1698] Prefill newest version for project migration
  engine-shared/elm/Shared/Data/PackageSuggestion.elm
  engine-wizard/elm/Wizard/Projects/Common/QuestionnaireMigrationCreateForm.elm
  engine-wizard/elm/Wizard/Projects/CreateMigration/Update.elm
Labels: feature

#665 [DSW-1687] Add 2FA
  engine-shared/elm/Shared/Api/Auth.elm
  engine-shared/elm/Shared/Api/Tokens.elm
  engine-shared/elm/Shared/Data/BootstrapConfig/AuthenticationConfig.elm
  engine-shared/elm/Shared/Data/BootstrapConfig/AuthenticationConfig/TwoFactorAuthConfig.elm
  engine-shared/elm/Shared/Data/EditableConfig/EditableAuthenticationConfig.elm
  engine-shared/elm/Shared/Data/EditableConfig/EditableTwoFactorAuthConfig.elm
  engine-shared/elm/Shared/Data/Token.elm
  engine-shared/elm/Shared/Data/TokenResponse.elm
  engine-shared/elm/Shared/Form/Validate.elm
  engine-wizard/elm/Wizard/Common/View/ActionButton.elm
  engine-wizard/elm/Wizard/Public/Auth/Msgs.elm
  engine-wizard/elm/Wizard/Public/Auth/Update.elm
  engine-wizard/elm/Wizard/Public/Login/Models.elm
  engine-wizard/elm/Wizard/Public/Login/Msgs.elm
  engine-wizard/elm/Wizard/Public/Login/Update.elm
  engine-wizard/elm/Wizard/Public/Login/View.elm
  engine-wizard/elm/Wizard/Settings/Authentication/View.elm
  engine-wizard/elm/Wizard/Settings/Common/Forms/AuthenticationConfigForm.elm
Labels: feature

#666 [DSW-1704] Fix main menu highlight for users
  engine-wizard/elm/Wizard/Routes.elm
Labels: bugfix

#667 [DSW-1705] Add uploading of text assets as files in document template…
  engine-shared/elm/Shared/Api/DocumentTemplateDrafts.elm
  engine-shared/elm/Shared/Data/DocumentTemplate/DocumentTemplateFile.elm
  engine-shared/elm/Shared/Error/ServerError.elm
  engine-wizard/elm/Wizard/Common/ContentType.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Editor/Components/FileEditor.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Editor/Components/FileEditor/AssetUploadModal.elm
Labels: feature

#668 [DSW-1709] Add chapter number to human identifier of question
  engine-wizard/elm/Wizard/Common/Components/Questionnaire.elm
Labels: feature

#669 [DSW-1694] Propagate questionnaire changes through websocket
  engine-shared/elm/Shared/Data/QuestionnaireDetail.elm
  engine-shared/elm/Shared/Data/WebSockets/QuestionnaireAction/SetQuestionnaireData.elm
  engine-shared/elm/Shared/Data/WebSockets/ServerQuestionnaireAction.elm
  engine-wizard/elm/Wizard/Common/Components/Questionnaire.elm
  engine-wizard/elm/Wizard/Projects/Detail/Update.elm
Labels: feature

#670 Hotfix 3.20.2
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Create/Update.elm
  package-lock.json
  package.json
  wizard-style-builder/package-lock.json
  wizard-style-builder/package.json
Labels: hotfix

#671 Hotfix 3.20.2 (develop)
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Create/Update.elm
  package-lock.json
  package.json
  wizard-style-builder/package-lock.json
  wizard-style-builder/package.json
Labels: hotfix

#672 Switch to Docker Hub for dev images
  .github/workflows/main.yml
Labels: chore

#681 Fix Docker build CI for Dependabot
  .github/workflows/main.yml
Labels: chore

#680 [DSW-1700] Prevent leaking tokens when downloading files
  engine-shared/elm/Shared/Api.elm
  engine-shared/elm/Shared/Api/DocumentTemplateDrafts.elm
  engine-shared/elm/Shared/Api/DocumentTemplates.elm
  engine-shared/elm/Shared/Api/Documents.elm
  engine-shared/elm/Shared/Api/Locales.elm
  engine-shared/elm/Shared/Api/Packages.elm
  engine-shared/elm/Shared/Api/Questionnaires.elm
  engine-shared/elm/Shared/Data/UrlResponse.elm
  engine-wizard/elm/Wizard/Common/FileDownloader.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Editor/Components/Preview.elm
  engine-wizard/elm/Wizard/DocumentTemplates/Detail/Msgs.elm
  engine-wizard/elm/Wizard/DocumentTemplates/Detail/Update.elm
  engine-wizard/elm/Wizard/DocumentTemplates/Index/Msgs.elm
  engine-wizard/elm/Wizard/DocumentTemplates/Index/Update.elm
  engine-wizard/elm/Wizard/Documents/Index/Msgs.elm
  engine-wizard/elm/Wizard/Documents/Index/Update.elm
  engine-wizard/elm/Wizard/KnowledgeModels/Detail/Msgs.elm
  engine-wizard/elm/Wizard/KnowledgeModels/Detail/Update.elm
  engine-wizard/elm/Wizard/Locales/Detail/Msgs.elm
  engine-wizard/elm/Wizard/Locales/Detail/Update.elm
  engine-wizard/elm/Wizard/Locales/Index/Msgs.elm
  engine-wizard/elm/Wizard/Locales/Index/Update.elm
  engine-wizard/elm/Wizard/Projects/Detail/Components/Preview.elm
  engine-wizard/elm/Wizard/Projects/Detail/Documents/Msgs.elm
  engine-wizard/elm/Wizard/Projects/Detail/Documents/Update.elm
Labels: feature

#684 [DSW-1720] Improve template editor
  engine-wizard/elm/Wizard/Common/Components/CodeEditor.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Editor/Components/FileEditor.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Editor/Components/FileEditor/Editor.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Editor/Components/FileEditor/EditorGroup.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Editor/Components/Preview.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Editor/DTEditorRoute.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Editor/Models.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Editor/Msgs.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Editor/Update.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Editor/View.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Models.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Routes.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Routing.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Subscriptions.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/Update.elm
  engine-wizard/elm/Wizard/DocumentTemplateEditors/View.elm
  engine-wizard/elm/Wizard/Routes.elm
  engine-wizard/elm/Wizard/Update.elm
  engine-wizard/js/components/code-editor.js
  engine-wizard/scss/elements/_file-tree.scss
  engine-wizard/scss/modules/Documents/_DocumentTemplateEditor.scss
Labels: feature

#685 [DSW-1732] Add authorization code description to 2FA
  engine-wizard/elm/Wizard/Public/Login/View.elm
Labels: feature

#686 [DSW-1723] Adjust Docker images to run under non-root user
  engine-registry/docker/Dockerfile
  engine-registry/docker/nginx/default.conf
  engine-wizard/docker/Dockerfile
  engine-wizard/docker/nginx/default.conf
Labels: feature

#693 Hotfix 3.20.3
  package-lock.json
  package.json
  wizard-style-builder/package-lock.json
  wizard-style-builder/package.json
Labels: hotfix

#692 Hotfix 3.20.3 (develop)
  package-lock.json
  package.json
  wizard-style-builder/package-lock.json
  wizard-style-builder/package.json
Labels: hotfix

#694 [DSW-1740] Allow to copy direct link to a question in project
  .github/workflows/main.yml
  engine-wizard/elm/Wizard/Common/AppState.elm
  engine-wizard/elm/Wizard/Common/Components/Questionnaire.elm
  engine-wizard/elm/Wizard/Common/Provisioning/DefaultIconSet.elm
  engine-wizard/elm/Wizard/Dashboard/Widgets/RecentProjectsWidget.elm
  engine-wizard/elm/Wizard/Documents/Index/View.elm
  engine-wizard/elm/Wizard/KMEditor/Editor/Components/Preview.elm
  engine-wizard/elm/Wizard/KnowledgeModels/Preview/Update.elm
  engine-wizard/elm/Wizard/Projects/Create/CustomCreate/Update.elm
  engine-wizard/elm/Wizard/Projects/Create/TemplateCreate/Update.elm
  engine-wizard/elm/Wizard/Projects/Detail/Components/QuestionnaireVersionViewModal.elm
  engine-wizard/elm/Wizard/Projects/Detail/Components/ShareModal.elm
  engine-wizard/elm/Wizard/Projects/Detail/Models.elm
  engine-wizard/elm/Wizard/Projects/Detail/ProjectDetailRoute.elm
  engine-wizard/elm/Wizard/Projects/Detail/Subscriptions.elm
  engine-wizard/elm/Wizard/Projects/Detail/Update.elm
  engine-wizard/elm/Wizard/Projects/Detail/View.elm
  engine-wizard/elm/Wizard/Projects/Import/Update.elm
  engine-wizard/elm/Wizard/Projects/Import/View.elm
  engine-wizard/elm/Wizard/Projects/Index/Update.elm
  engine-wizard/elm/Wizard/Projects/Index/View.elm
  engine-wizard/elm/Wizard/Projects/Migration/Update.elm
  engine-wizard/elm/Wizard/Projects/Models.elm
  engine-wizard/elm/Wizard/Projects/Routing.elm
  engine-wizard/elm/Wizard/Routes.elm
Labels: feature

#695 [DSW-1741] Show warning on imports
  engine-wizard/elm/Wizard/DocumentTemplates/Import/FileImport/View.elm
  engine-wizard/elm/Wizard/KnowledgeModels/Import/FileImport/Update.elm
  engine-wizard/elm/Wizard/KnowledgeModels/Import/FileImport/View.elm
  engine-wizard/elm/Wizard/Locales/Import/FileImport/View.elm
Labels: feature

#696 [DSW-1742] Fix wrong error code on project document preview
  engine-wizard/elm/Wizard/Projects/Detail/Components/Preview.elm
Labels: bugfix

#697 [DSW-1743] Rename upload button to import on import screens
  engine-wizard/elm/Wizard/DocumentTemplates/Import/FileImport/View.elm
  engine-wizard/elm/Wizard/KnowledgeModels/Import/FileImport/View.elm
  engine-wizard/elm/Wizard/KnowledgeModels/Import/OwlImport/View.elm
  engine-wizard/elm/Wizard/Locales/Import/FileImport/View.elm
Labels: chore

#698 [DSW-1746] Add version of registry to the UI
  engine-registry/elm/Registry.elm
  engine-registry/elm/Registry/Common/AboutModal.elm
  engine-registry/elm/Registry/Common/Requests.elm
  engine-registry/scss/Common/_AboutModal.scss
  engine-registry/scss/Common/_Modal.scss
  engine-registry/scss/_Common.scss
Labels: feature

#700 Update style builder build
  .github/workflows/wizard-style-builder.yml
Labels: chore

#699 [DSW-1744] Rename support repository in support settings
  engine-shared/elm/Shared/Data/BootstrapConfig/PrivacyAndSupportConfig.elm
  engine-wizard/elm/Wizard/Common/Menu/View.elm
  engine-wizard/elm/Wizard/Common/Provisioning/DefaultIconSet.elm
  engine-wizard/elm/Wizard/Settings/Common/FontAwesome.elm
  engine-wizard/elm/Wizard/Settings/LookAndFeel/View.elm
  engine-wizard/elm/Wizard/Settings/PrivacyAndSupport/View.elm
Labels: feature

#701 [DSW-1748] Fix profile menu border overflow
  engine-wizard/scss/_layout.scss
Labels: bugfix

#704 [DSW-1767] Add possibility to include custom scripts
  engine-wizard/docker/start.sh
Labels: feature
