Repository ds-wizard/engine-frontend, pull requests merged in 2024-07, with the labels that each got.

#1179 Release 4.8.0 (develop)
  package-lock.json
  package.json
Labels: release

#1183 Hotfix 4.8.1
  engine-registry/docker/Dockerfile
  engine-wizard/docker/Dockerfile
  package-lock.json
  package.json
Labels: hotfix

#1184 Hotfix 4.8.1 (develop)
  engine-registry/docker/Dockerfile
  engine-wizard/docker/Dockerfile
  package-lock.json
  package.json
Labels: hotfix

#1182 Push release Docker images to private repo
  .github/workflows/registry.yml
  .github/workflows/wizard.yml
Labels: chore
